{% set name = "ffi" %}
{% set version = "1.11.3" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 6da2eb3c4867e64df28d3e0b1008422dfacda7c046f9a8f3c56c52505b195e81

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/ffi_c clean
  skip: {{ win }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ruby
    - libffi
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Ruby FFI library

  doc_url: https://github.com/ffi/ffi/wiki
  dev_url: https://github.com/ffi/ffi

extra:
  recipe-maintainers:
    - sodre
