{% set name = "ffi" %}
{% set version = "1.14.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 7dce3fe0f047a6f774d141d4667c9d23ee28c8dc72fbef6194dca398808f0f96

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/ffi_c clean
  skip: {{ win }}
  skip: true  # [ruby == "2.5" and osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make                 # [unix]
  host:
    - ruby
    - libffi
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Ruby FFI library

  doc_url: https://github.com/ffi/ffi/wiki
  dev_url: https://github.com/ffi/ffi

extra:
  recipe-maintainers:
    - sodre
