travis:
  secure:
    BINSTAR_TOKEN: raA5q6ADKaKXiRq8Pm1qwkS47HdrTIYejG+5/PllPBCdqg1bOXC9YO78oZuXH8aBXaJCdbxgRarT72k6AAANsPMNLP3Jkdl+wqoc2+5SzzTfhJ6l6G7dENndCk4IbsXQLjg14fl3AqFS9e5S6NICf03IB5rjxdX6yEHsxPzEkq7d7Q1A5lst57AkwMhRScZx0kXvUDYZEmx/GFGDNounp8BDGJLrweOA1nb8VycNIPiZ8MNfiWU9Ib9JPGNLpEnGbb8fzq/g6KgWkGRfHIFDQyau9sbX2o6QnMbC/QvBw1+eClPp03Pzsz3P2b/TRXz/XzH/g1l4JbmHGtkw/w9ZT3cDa7beOjg/wb47FdcR1WBjt9+jMux6aSUqrccrS2KHrR7yTpoE2IhppoAl0vYoEUSZceeQP3woYG3SyDW0JJohPgnWRNq+l0K3bz4I0UwwQO69zj3ouPssiduQ6q90zQuhW2lG3JyV4teJm9QwW8N/pRNBRsSF8MY6Z/3OXbUC7RGEPdQMAviQVrDi3TOyxwrWmv7dSWFw1tcxL5g68Fmcrft6P+V9PIoyMH3OxxGe0PaHs0533iG6g9uGnZTBa/ppUucx3bsZg7iH+bKGsKA8NvkwBPw/FvGp/EHrxZ+mHOUzgibkuniRf6BprdBKm89QULQARNZfLl6WfRdyw+A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
